AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  My Python Lambda Application to send an MT700 details

Globals:
  Function:
    Timeout: 30

Resources:
  MT700SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambdafunction.lambda_handler
      Runtime: python3.12
      
      Role: !GetAtt MT700SendEmailFunctionRole.Arn

      Events:
        SendEmailApiEvent:
          Type: Api
          Properties:
            Path: /sendemail
            Method: POST

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: "ses:SendRawEmail"
              Resource: "*"

  SendEmailApiEndpoint:
    Description: "API Gateway endpoint URL for the email sending service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/sendemail"